<?php

$key = [
    'String',
    'int',
    'grd',
    'Subject',
    'String',
    'return',
    'course',
    'String',
    'this',
    'int',
    'void',
    'String',
    'grade',
    'String',
    'grade',
    'Vector',
    'Subject',
    'int',
    'this.year',
    'Vector',
    'String',
    'return',
    'this.lastName',
    'String',
    'firstName',
    'getYear',
    'int year',
    'Vector<Subject>',
    'subjects',
    'void',
    'Subject',
    'subjects',
    'float',
    'subjects',
    'getGrade',
    'size',
    'lastName',
    'firstName',
    'program',
    'year',
    'Villaber, Sharon BSCS-1',
    'Al Fahsaad, Hamir BSCRIM-2',
    'Villaber, Sharon BSCS-1',
    '90',
    'College Orientation',
    '85.5',
    '89',
    '89',
    '4',
    'REED 201 : 90'
];